[service]
Name = "go.http.srv.pusher"
Version = "v1"
RegisterTTL = 1
RegisterInterval = 1

[web]
Host = "0.0.0.0"
Port = 8012

[pusher]
auth = true
secret = "abc"

[circuitBreaker]
    [circuitBreaker."go.micro.srv.s2"] #target service
    MaxRequests = 100
    CountsRequests = 1000
    FailureRatio = 0.6 #calculate in 30s/Requests
    Interval = 30 #closed clean every 30s
    Timeout = 90 #open->halfopen after 30s

    [circuitBreaker."go.micro.srv.s3"]
    MaxRequests = 100
    CountsRequests = 1000
    FailureRatio = 0.6 #calculate in 30s/Requests
    Interval = 30 #closed clean every 30s
    Timeout = 90 #open->halfopen after 30s

[rateLimit]
ClientRate = 2000.0
ClientCapacity = 10000
ClientWait = false
ServerRate = 2000.0
ServerCapacity = 10000
ServerWait = false