[service]
Name = "go.micro.srv.pusher"
Version = "v1"
RegisterTTL = 30
RegisterInterval = 20

[web]
Host = "0.0.0.0"
Port = 8012

[pusher]
Auth = true
Secret = "abc"

[circuitBreaker]
MaxRequests = 2
CountsRequests = 6

[rateLimit]
ClientRate = 2000.0
ClientCapacity = 10000
ClientWait = false
ServerRate = 2000.0
ServerCapacity = 10000
ServerWait = false