[kafka]
Brokers = [
    "127.0.0.1:9092",
    "127.0.0.2:9092",
    "127.0.0.3:9092"
]

Zkaddrs = [
    "127.0.0.1:2181",
    "127.0.0.2:2181",
    "127.0.0.3:2181"
]

Zkroot = "/kafka"
Topic = "zlog"
Group = "zipkin"
CommitInterval = 10
ProcessingTimeout = 10
ZookeeperTimeout = 3000
