[service]
Name = "go.http.srv.pusher"
Version = "v1"
RegisterTTL = 1
RegisterInterval = 1

[web]
Host = "0.0.0.0"
Port = 8012

[pusher]
auth = true
secret = "abc"

[circuitBreaker]
MaxRequests = 2
CountsRequests = 6

[rateLimit]
ClientRate = 2000.0
ClientCapacity = 10000
ClientWait = false
ServerRate = 2000.0
ServerCapacity = 10000
ServerWait = false