InstanceName = "CrawlerCluster"
PoolSize = 10
IsCluster = true

[[master]]
DB = "0"
IP = "127.0.0.1"
Port = "29010"

[[master]]
DB = "0"
IP = "127.0.0.1"
Port = "29011"

[[slave]]
DB = "0"
IP = "127.0.0.1"
Port = "29012"

[[slave]]
DB = "0"
IP = "127.0.0.1"
Port = "29013"