InstanceName = "BGCrawler" #InstanceName is base key
DBName = "Crawler"

[readwrite]
Server = "127.0.0.1"
Port = "3306"
UserID = "dev"
Password = "123"
CharSet = "utf8mb4"

[readonly]
Server = "127.0.0.1"
Port = "3306"
UserID = "dev"
Password = "123"
CharSet = "utf8mb4"